language: go
go:
- 1.3
env:
  matrix:
  - PATH=/home/travis/gopath/bin:$PATH
  global:
    secure: BgygmNQJSxx6Grkwc4tX0Pzl8+G7SVh4zB3/x1P3CBhvsLH39hkI1+6gzsUtHR8jfevTW9RkUXBsn1Fw9JDdaz8tm60ay2vKUCqEwlA3EYn6rzZnKtST5bO3TaO5Y2KGwHe0OZVhgA1QyijUoxNmczfnXTTy/Triy01XcR6GFeg=
install:
- go get github.com/mitchellh/gox
- gox -build-toolchain -osarch=linux/386
- sudo apt-get update
- DEBIAN_FRONTEND=noninteractive sudo apt-get install -y rpm devscripts debhelper
- mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
script:
- make all
after_success:
- echo -e "Host github.com\n\tStrictHostKeyChecking no\nIdentityFile ~/.ssh/deploy.key\n" >> ~/.ssh/config
- openssl aes-256-cbc -k "$SERVER_KEY" -in tool/travis/autotag_deploy_key.enc -d -a -out ../deploy.key
- cp ../deploy.key ~/.ssh/
- chmod 600 ~/.ssh/deploy.key
- git remote set-url origin git@github.com:mackerelio/mackerel-agent-plugins.git
- tool/autotag
deploy:
  provider: releases
  api_key:
    secure: c2pLKkM2leWMIzakVisNf3kAK6TBYslDM8SFEVrTTHpHnTI/6jUFnDLuL9cKuq9c76QcgYfqdLDn/hP+uFHf5WdtdJR00R+bX8cCx6NfOe7Kk9GlqGinUcXKAVs0kQHaYtQrN/rCOIG92kYFdbRHMD8uMrADJVRySePTMMhMX9o=
  file:
  - "/home/travis/rpmbuild/RPMS/noarch/mackerel-agent-plugins-0.5.0-1.noarch.rpm"
  - "/home/travis/gopath/src/github.com/mackerelio/mackerel-agent-plugins/packaging/mackerel-agent-plugins_0.5.0-1_all.deb"
  skip_cleanup: true
  on:
    repo: mackerelio/mackerel-agent-plugins
    all_branches: true
    tags: true
notifications:
  slack:
    secure: cPeJRg+ouTlemEV5UM4muhDwtIM0dktcs3mnfB73oZ2MGOimv/DFpL+VTRLlkWau8l0dT4ngLlGPcveLrXQXwps2LsJMr+gS6Az/CAQCIl21oj4bnjs5uGYTG8hM8ymVzGINPNnj5Fnn5DUMunA2sow30qxfuCnSUMGot2nFRKw=
