language: go

go:
  - 1.3
env: "PATH=/home/travis/gopath/bin:$PATH"
install:
    - go get github.com/mitchellh/gox
    - gox -build-toolchain -osarch=linux/386
    - go get -d -v ./... && go build -v ./...
    - sudo apt-get update
    - DEBIAN_FRONTEND=noninteractive sudo apt-get install -y rpm
    - mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}

script:
    - go test -v ./...
    - make
